"""Add retry metadata

Revision ID: 3e27eeab916a
Revises: 2e1fbffa24b6
Create Date: 2026-08-26 11:09:54.201661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e27eeab916a'
down_revision: Union[str, Sequence[str], None] = '2e1fbffa24b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('recovery_decisions', sa.Column('execution_attempts', sa.Integer(), nullable=False))
    op.add_column('recovery_decisions', sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recovery_decisions', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('recovery_decisions', sa.Column('last_error_type', sa.String(length=128), nullable=True))
    op.add_column('recovery_decisions', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_decisions', 'next_retry_at')
    op.drop_column('recovery_decisions', 'last_error_type')
    op.drop_column('recovery_decisions', 'last_error')
    op.drop_column('recovery_decisions', 'execution_started_at')
    op.drop_column('recovery_decisions', 'execution_attempts')

    # ### end Alembic commands ###
